### PR TITLE
Fix test cases mainly in AddCommandPaserTest and EditCommandPaserTest

### PR DESCRIPTION
**Pull request by JulietTeoh**
From my eyeballing, the main test case left to fix is NameContainsKeywordsPredicateTest.java

### CODE REVIEW

**Comment by JulietTeoh** [comment]
@tjtanjin the run and send test lowly unreliable they sometimes pass sometimes fail on my comp and I couldn't even commit my work on sourcetree.

**Review by tjtanjin — APPROVED** [review]
LGTM! :)

**Comment by tjtanjin** [comment]
> @tjtanjin the run and send test lowly unreliable they sometimes pass sometimes fail on my comp and I couldn't even commit my work on sourcetree.

Strange if it's inconsistent, if it happens again can create an issue for it and then paste screenshots of the error messages easier to debug :D

**Comment by tlylt** [comment]
> @tjtanjin the run and send test lowly unreliable they sometimes pass sometimes fail on my comp and I couldn't even commit my work on sourcetree.

Yes @JulietTeoh if run & send have issues, please include in the error message so that I can take a look 👁️

**Pull request merged**
